### ISSUE TITLE
logstash-config: how to configure patterns

### ISSUE THREAD

**Issue by greg0ire** [rancher/compose-templates#89]
I can't figure out how to use [the confd patterns](https://github.com/rancher/catalog-dockerfiles/blob/master/logstash/containers/0.2.0/logstash-config/conf.d/patterns.toml#L5) key.

Is it supposed to work yet? It is not documented ATM.

I noticed that [the patterns template](https://github.com/rancher/catalog-dockerfiles/blob/master/logstash/containers/0.2.0/logstash-config/templates/patterns.tmpl#L1) uses config keys that do not have the `/self/service/metadata` part like [in the config template](https://github.com/rancher/catalog-dockerfiles/blob/master/logstash/containers/0.2.0/logstash-config/templates/logstash.conf.tmpl).

I tried configuring rancher like this :

```yml
logstash:
  metadata:
    logstash:
      patterns:
        - ${indexer_patterns}
```

and like this:

```yml
logstash:
  metadata:
    logstash:
      patterns:
        - |
          ${indexer_patterns}
```

But the patterns file stays empty… @cloudnautique, maybe you can help?
